"""Add l1_ratio column to RegularizationConfiguration

Revision ID: 3e0204e4c38d
Revises: cfffe56e15bb
Create Date: 2016-07-30 16:17:21.765565

"""

# revision identifiers, used by Alembic.
revision = '3e0204e4c38d'
down_revision = 'cfffe56e15bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regularization_configs', sa.Column('l1_ratio', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regularization_configs', 'l1_ratio')
    ### end Alembic commands ###
