"""Test?

Revision ID: 8245e99ebd1a
Revises: 85a5242fe77c
Create Date: 2016-07-30 16:41:34.432495

"""

# revision identifiers, used by Alembic.
revision = '8245e99ebd1a'
down_revision = '85a5242fe77c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
