"""Fix spelling error in threshold

Revision ID: 85a5242fe77c
Revises: 3e0204e4c38d
Create Date: 2016-07-30 16:36:48.591277

"""

# revision identifiers, used by Alembic.
revision = '85a5242fe77c'
down_revision = '3e0204e4c38d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solver_configs', sa.Column('threshold', sa.FLOAT(), server_default=sa.text(u"'0.0'"), autoincrement=False, nullable=False))
    op.drop_column('solver_configs', 'treshold')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solver_configs', sa.Column('treshold', sa.FLOAT(), server_default=sa.text(u"'0.0'"), autoincrement=False, nullable=False))
    op.drop_column('solver_configs', 'threshold')
    ### end Alembic commands ###
