"""Autoincrement

Revision ID: acff0fd64f68
Revises: 8245e99ebd1a
Create Date: 2016-07-30 18:11:05.747669

"""

# revision identifiers, used by Alembic.
revision = 'acff0fd64f68'
down_revision = '8245e99ebd1a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
