"""Make cv non-null.

Revision ID: c1ca85d1979b
Revises: 63580b4db2df
Create Date: 2016-08-09 16:44:34.030723

"""

# revision identifiers, used by Alembic.
revision = 'c1ca85d1979b'
down_revision = '63580b4db2df'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiments', 'cv',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiments', 'cv',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    ### end Alembic commands ###
