"""Initial revision

Revision ID: c6a0ad47e421
Revises: 
Create Date: 2016-07-29 18:31:46.100171

"""

# revision identifiers, used by Alembic.
revision = 'c6a0ad47e421'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
