"""Add cv-std to db

Revision ID: c9f1fb08ea57
Revises: c1ca85d1979b
Create Date: 2016-08-24 16:17:51.144091

"""

# revision identifiers, used by Alembic.
revision = 'c9f1fb08ea57'
down_revision = 'c1ca85d1979b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('validation_std', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'validation_std')
    ### end Alembic commands ###
