"""Add treshold column to SolverConfigs

Revision ID: cfffe56e15bb
Revises: c6a0ad47e421
Create Date: 2016-07-29 18:34:09.434999

"""

# revision identifiers, used by Alembic.
revision = 'cfffe56e15bb'
down_revision = 'c6a0ad47e421'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solver_configs', sa.Column('treshold', sa.Float(), nullable=False, server_default='0.0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solver_configs', 'treshold')
    ### end Alembic commands ###
